# Generated by Django 6.0.3 on 2026-04-02 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('weight', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REOPENED', 'Reopened')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='org.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SELF', 'Self'), ('PEER', 'Peer'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavioral_submissions_made', to='org.employee')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_submissions', to='appraisals.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('half', models.CharField(choices=[('H1', 'H1'), ('H2', 'H2')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'half'), name='uniq_cycle_year_half')],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='appraisals.evaluationcycle'),
        ),
        migrations.CreateModel(
            name='BehavioralScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='appraisals.behavioralattribute')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='appraisals.behavioralsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'attribute'), name='uniq_submission_attribute')],
            },
        ),
        migrations.AddConstraint(
            model_name='behavioralsubmission',
            constraint=models.UniqueConstraint(fields=('evaluation', 'role', 'submitted_by'), name='uniq_submission'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'cycle'), name='uniq_eval_employee_cycle'),
        ),
    ]
