# Generated by Django 6.0.3 on 2026-04-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_peerassignment'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SELF', 'Self'), ('PEER', 'Peer'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('attribute_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('FINAL', 'Final')], default='DRAFT', max_length=20)),
                ('task_score_70', models.FloatField(default=0.0)),
                ('behavior_score_30', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('weight_a', models.FloatField()),
                ('goal_b', models.FloatField()),
                ('actual_c', models.FloatField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='behavioralscore',
            name='uniq_submission_attribute',
        ),
        migrations.RemoveConstraint(
            model_name='behavioralsubmission',
            name='uniq_submission',
        ),
        migrations.RemoveConstraint(
            model_name='evaluation',
            name='uniq_eval_employee_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='evaluationcycle',
            name='uniq_cycle_year_half',
        ),
        migrations.RemoveConstraint(
            model_name='peerassignment',
            name='uniq_peer_assignment',
        ),
        migrations.AddField(
            model_name='peerassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peerassignment',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.employee'),
        ),
        migrations.AddField(
            model_name='behaviorrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.employee'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.employee'),
        ),
        migrations.AddField(
            model_name='behaviorrating',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_ratings', to='appraisals.performanceevaluation'),
        ),
        migrations.AlterField(
            model_name='peerassignment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_peers', to='appraisals.performanceevaluation'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='appraisals.performanceevaluation'),
        ),
        migrations.RemoveField(
            model_name='behavioralscore',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='behavioralscore',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='behavioralsubmission',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='behavioralsubmission',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='peerassignment',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='BehavioralAttribute',
        ),
        migrations.DeleteModel(
            name='BehavioralScore',
        ),
        migrations.DeleteModel(
            name='BehavioralSubmission',
        ),
        migrations.DeleteModel(
            name='EvaluationCycle',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
